### PR TITLE
0.8.0 rc

### PR DESCRIPTION
**Pull request by oliveira131**
Just a suggestion of changes for probable 0.8 version with new options and more colors support.

Captura de Tela 2019-07-22 às 13 40 20

### CODE REVIEW

**Comment by Script47** [comment]
@oliveira131 this looks good. The only suggestion I'd make is to update the example.

**Comment by oliveira131** [comment]
I update the index.html file in example folder with samples for icon and prepend toasts.
Captura de Tela 2019-07-22 às 21 41 04

**Review by Script47 — APPROVED** [review]
@oliveira131 

Thanks for these extensive changes.

**Review by Script47 — CHANGES_REQUESTED** [review]
@oliveira131  

Thanks for the extensive changes (and apologies for the delay).

Any chance you could update the minfied JS source too and then I'll merge the pull.

**Comment by Script47** [comment]
Thanks for your PR.

With the changes of #24 you can now apply styles to the various types so I'm closing this PR.

**Pull request closed without merging**
